name: stoi
system: stoi
stoi_sample_rate: 10000   # Sample rate for STOI computation
batch: 1
n_batches: 1

separator:
  keep_vocals: False # Set to True if you want to keep the separated vocals
  sample_rate: 44100 # sample_rate of the separation model

reference: unprocessed